export type AnalogyDomain = "Cooking" | "Music" | "Sports" | "Home Depot";

export type GlossaryEntry = {
  term: string;
  pronunciation?: string;
  plain: string;
  technical: string;
  analogyDomain: AnalogyDomain;
  analogy: string;
  why: string;
  misconception: string;
};

export const GLOSSARY: GlossaryEntry[] = [
  {
    term: "Classical bit",
    plain: "A classical bit is the smallest unit of ordinary computer information. After you look at it, it is either 0 or 1.",
    technical: "A bit is a binary variable with a definite value in {0, 1}. Classical circuits transform bits with logic gates such as AND, OR, and NOT.",
    analogyDomain: "Home Depot",
    analogy: "A light switch that is either off or on when you look at it. Checking the switch does not put it into a new state. It was already one or the other.",
    why: "Almost every comparison in this workshop starts here. Quantum computing adds a different kind of information. It does not throw the bit away.",
    misconception: "A qubit is a bit that can be both numbers in a way that tries every answer at once. That picture is easy to pick up, and we will build a clearer one together.",
  },
  {
    term: "Qubit",
    pronunciation: "KYOO-bit",
    plain: "A qubit is the basic unit of quantum information. Before measurement it is described by a quantum state, not by a single stored 0 or 1.",
    technical: "A qubit’s pure state is a normalized vector in a two-dimensional complex vector space, spanned by the basis states |0⟩ and |1⟩.",
    analogyDomain: "Music",
    analogy: "A note that has not been recorded yet. You can shape its loudness and its timing. When you record it, the recording is one definite sample.",
    why: "Every circuit in Composer and Qiskit changes qubit states and then measures them.",
    misconception: "A qubit is a tiny classical bit that spins until you look. The useful description is a statevector, not a spinning coin.",
  },
  {
    term: "State",
    plain: "The state is the complete description of what we know about the qubits before we measure them.",
    technical: "For an isolated pure state of n qubits, the state is a normalized vector with 2ⁿ amplitudes, one for each computational basis string.",
    analogyDomain: "Cooking",
    analogy: "The state is the bowl after you have mixed the ingredients and before you plate a serving. The recipe so far is written down. The serving you scoop is the measurement.",
    why: "Gates change the state. Measurement samples it. If you skip the state, the histogram looks like magic.",
    misconception: "The state is the histogram. The histogram is a record of many measurements. The state is the description before those measurements.",
  },
  {
    term: "Statevector",
    pronunciation: "STATE-vek-ter",
    plain: "A statevector is the list of amplitudes that describes a quantum state.",
    technical: "In the computational basis, an n-qubit statevector is a column of 2ⁿ complex numbers whose squared magnitudes sum to 1.",
    analogyDomain: "Music",
    analogy: "A chord chart that lists every note in the chord and how loud each one is, including a timing offset. It is the whole chord, not one plucked string.",
    why: "In the Python lab we print the statevector before we measure, so you can see the state Composer is also tracking.",
    misconception: "A longer statevector means a better quantum computer. The length is 2ⁿ because there are 2ⁿ basis states, not because the device is more powerful by itself.",
  },
  {
    term: "Basis state",
    pronunciation: "BAY-sis",
    plain: "A basis state is one of the definite labels we use to write a state, such as |0⟩, |1⟩, |00⟩, or |11⟩.",
    technical: "The computational basis is the orthonormal set of states labeled by classical bit strings. Any statevector is a weighted sum of these states.",
    analogyDomain: "Sports",
    analogy: "The scoreboard categories. A final score lands in one category. A play before the whistle can be a mixture of possibilities, written as a combination of those categories.",
    why: "Gates and measurements are defined by what they do to basis states.",
    misconception: "Only basis states are real. Superpositions are also valid states. A basis state is a convenient label.",
  },
  {
    term: "Amplitude",
    plain: "An amplitude is the complex number in front of a basis state. It is not the probability itself.",
    technical: "If the state is Σ αₓ |x⟩, the amplitude αₓ is complex. The probability of reading x is |αₓ|², provided the state is normalized.",
    analogyDomain: "Music",
    analogy: "The volume knob and the timing of one note in a chord. Volume contributes to how likely that note is to dominate. Timing is the phase, and it matters when notes combine.",
    why: "Two states can have the same probabilities and different amplitudes. Interference depends on that difference.",
    misconception: "Amplitude and probability are the same number. You square the magnitude of the amplitude to get the probability.",
  },
  {
    term: "Probability",
    plain: "A probability is the chance of a particular measurement result. It is between 0 and 1, and all the chances together add up to 1.",
    technical: "For a computational-basis measurement, P(x) = |αₓ|². In an ideal simulation with many shots, the fraction of shots equal to x approaches P(x).",
    analogyDomain: "Sports",
    analogy: "A shooting percentage. One shot can miss. A large number of shots shows the percentage you prepared.",
    why: "Histograms are pictures of probabilities estimated from shots, not the state itself.",
    misconception: "If the probability is one half, a single shot must come out half 0 and half 1. One shot is one result.",
  },
  {
    term: "Phase",
    pronunciation: "fayz",
    plain: "Phase is the part of an amplitude that changes how states combine, even when the probabilities look the same.",
    technical: "A complex amplitude can be written as r·e^{iφ}. The angle φ is the phase. Relative phases between amplitudes control interference.",
    analogyDomain: "Music",
    analogy: "Two speakers playing the same note. If one is slightly delayed, the room can get louder or quieter even though each speaker’s volume knob did not move.",
    why: "Some gates change probabilities. Some mainly change phase. Both matter.",
    misconception: "Phase is a physical angle you can see on the chip. It is part of the mathematical description of the state.",
  },
  {
    term: "Superposition",
    pronunciation: "SOO-per-puh-ZISH-un",
    plain: "A superposition is a state that is a combination of basis states, with amplitudes, before measurement.",
    technical: "A state is a superposition when more than one computational-basis amplitude is nonzero. Measurement in that basis yields one basis state, with probability given by the squared magnitudes.",
    analogyDomain: "Cooking",
    analogy: "A sauce that has been seasoned but not plated. The recipe contains more than one possible serving. Plating gives you one serving. The sauce was not secretly two finished plates at the same time.",
    why: "The Hadamard gate in the Bell lab creates a superposition on qubit 0. Without it, the CNOT has nothing interesting to correlate.",
    misconception: "Superposition means the qubit is 0 and 1 at the same time and therefore tries every answer. It means the state is a weighted combination, and a measurement returns one outcome.",
  },
  {
    term: "Entanglement",
    pronunciation: "en-TANG-gull-ment",
    plain: "Entanglement is a correlation between qubits that cannot be written as each qubit having its own separate state.",
    technical: "A multi-qubit pure state is entangled when it cannot be factored into a tensor product of single-qubit states. The Bell state (|00⟩ + |11⟩)/√2 is entangled.",
    analogyDomain: "Sports",
    analogy: "Two teammates who do not each have a separate plan. When you check them, their results match in a way that was prepared together. One player’s card does not tell the whole play.",
    why: "The Composer lab builds this correlation with H and CNOT. The histogram is a clue, not a full proof.",
    misconception: "Seeing only 00 and 11 once proves entanglement forever. Those counts are consistent with this preparation. A single computational-basis histogram is not a complete experimental proof.",
  },
  {
    term: "Quantum gate",
    plain: "A quantum gate is an operation that changes the state of one or more qubits.",
    technical: "A gate is a unitary operator on the state space. It is reversible, unlike a measurement.",
    analogyDomain: "Cooking",
    analogy: "A step in a recipe that changes the bowl: whisk, fold, or rest. It does not serve the dish. Serving is measurement.",
    why: "Circuits are ordered lists of gates, then optional measurements.",
    misconception: "A gate measures the qubit. A gate changes the state. Measurement is a separate step.",
  },
  {
    term: "Hadamard gate",
    pronunciation: "HAD-uh-mard",
    plain: "The Hadamard gate, written H, takes |0⟩ into an equal superposition of |0⟩ and |1⟩.",
    technical: "H|0⟩ = (|0⟩ + |1⟩)/√2 and H|1⟩ = (|0⟩ − |1⟩)/√2. Applying H twice returns the original basis state.",
    analogyDomain: "Music",
    analogy: "Splitting one tone into two equal speakers. The volume of each path becomes equal. A second split, done the same way, can bring you back.",
    why: "It is the first gate in the Bell-state lab.",
    misconception: "H always randomizes a qubit. On |0⟩ it creates equal probabilities. On a superposition it can also undo that superposition.",
  },
  {
    term: "X gate",
    plain: "The X gate flips |0⟩ and |1⟩, like a classical NOT, when the qubit is in a basis state.",
    technical: "X is the Pauli X operator. X|0⟩ = |1⟩ and X|1⟩ = |0⟩. On a superposition it exchanges the amplitudes of |0⟩ and |1⟩.",
    analogyDomain: "Home Depot",
    analogy: "A switch that flips off to on, or on to off, when the circuit is in a definite setting. If the state is a superposition, X swaps the two amplitudes rather than revealing a new measurement.",
    why: "One of the beginner challenges replaces H with X so you can see the Bell lab fall apart in a predictable way.",
    misconception: "X creates superposition. X flips basis states. H creates the equal superposition we use here.",
  },
  {
    term: "CNOT or CX gate",
    pronunciation: "SEE-not, or controlled-X",
    plain: "CNOT, also called CX, flips the target qubit when the control qubit is |1⟩.",
    technical: "CX|00⟩ = |00⟩, CX|01⟩ = |01⟩, CX|10⟩ = |11⟩, CX|11⟩ = |10⟩, with the control written first in this sentence. In Qiskit’s little-endian bitstrings, read the rightmost bit as qubit 0.",
    analogyDomain: "Home Depot",
    analogy: "A three-way dependency: the second fixture changes only if the first fixture is on. If the first fixture is in a superposition, the dependency ties the two results together.",
    why: "H on qubit 0 followed by CX onto qubit 1 prepares the Bell state in this lab.",
    misconception: "CNOT copies a qubit. It correlates the target with the control. Quantum information cannot be cloned.",
  },
  {
    term: "Control qubit",
    plain: "The control qubit is the qubit that decides whether a controlled gate acts.",
    technical: "In CX, the control selects the subspace in which X is applied to the target. The control itself is not flipped by an ideal CX.",
    analogyDomain: "Sports",
    analogy: "The player who calls the play. The call changes what the teammate does. Making the call is not the same as running the route.",
    why: "In the lab, qubit 0 is the control. Swapping control and target prepares a different wiring, even if the picture looks similar.",
    misconception: "The control is always the top wire. It is whichever qubit you attach the solid dot to.",
  },
  {
    term: "Target qubit",
    plain: "The target qubit is the qubit a controlled gate may change.",
    technical: "For CX, X acts on the target in the subspace where the control is |1⟩.",
    analogyDomain: "Sports",
    analogy: "The teammate who runs the route when the play is called.",
    why: "In this lab the target is qubit 1. The plus symbol on that wire is the X.",
    misconception: "The target is measured first. Measurement order on the diagram is left to right, and both qubits are measured at the end.",
  },
  {
    term: "Quantum circuit",
    plain: "A quantum circuit is a sequence of gates, and usually measurements, drawn or written in time order.",
    technical: "A circuit specifies unitary operations on quantum registers and, when measurements are present, maps results into classical bits.",
    analogyDomain: "Cooking",
    analogy: "A recipe card read from left to right: prep, combine, then plate. The wires are the ingredients that stay in the bowls. The boxes are the steps.",
    why: "Composer and Qiskit are two ways to write the same circuit.",
    misconception: "A circuit is the quantum computer. The circuit is the program. A simulator or QPU is where you run it.",
  },
  {
    term: "Quantum register",
    plain: "A quantum register is the group of qubits a circuit uses.",
    technical: "In Qiskit, QuantumCircuit(2) creates a quantum register of two qubits, indexed 0 and 1.",
    analogyDomain: "Home Depot",
    analogy: "The pair of labeled bins you set on the workbench before you start. Bin 0 and bin 1 stay distinct.",
    why: "Indexing starts at 0. Qubit 0 is the first qubit, not “qubit number 1” in everyday counting.",
    misconception: "Register size is the number of shots. Shots are repeats. The register is how many qubits the circuit has.",
  },
  {
    term: "Classical register",
    plain: "A classical register is the group of ordinary bits that store measurement results.",
    technical: "measure_all() adds a classical bit for each qubit and measures into it. The default name in the sampler result is meas.",
    analogyDomain: "Cooking",
    analogy: "The ticket the kitchen prints when a dish leaves the pass. The ticket is classical. The bowl before plating was the quantum state.",
    why: "Counts are tallies of those measurement results.",
    misconception: "Classical bits in the circuit are qubits. They are the ordinary record of results.",
  },
  {
    term: "Measurement",
    plain: "Measurement asks a qubit for a classical result. You get one basis outcome, not the full list of amplitudes.",
    technical: "A computational-basis measurement samples a bit string x with probability |αₓ|² and leaves the system in the corresponding basis state.",
    analogyDomain: "Cooking",
    analogy: "Plating one serving. You do not plate the whole recipe’s list of possible seasonings. You get one plate, and the bowl you scooped from is no longer the unplated sauce.",
    why: "The lab measures only after you have inspected the statevector of the unmeasured circuit.",
    misconception: "Measuring shows the amplitudes. It samples an outcome. Amplitudes are visible in the statevector or in Composer’s state tools, not in one click of a measurement.",
  },
  {
    term: "Shot",
    plain: "A shot is one run of the circuit that ends in one measurement result.",
    technical: "The shots argument tells a sampler how many times to sample the measured circuit.",
    analogyDomain: "Sports",
    analogy: "One free throw. The percentage comes from many free throws, not from one.",
    why: "We use 1024 shots so the histogram is stable enough to talk about, and a challenge asks you to try 100.",
    misconception: "More shots make the quantum computer more correct. More shots estimate the same probabilities more smoothly. They do not remove hardware noise.",
  },
  {
    term: "Counts",
    plain: "Counts are how many shots produced each bitstring.",
    technical: "A counts dictionary maps bitstrings to integers. The values sum to the number of shots.",
    analogyDomain: "Home Depot",
    analogy: "A tally sheet at the register: how many customers bought item 00 and how many bought item 11.",
    why: "The Python lab prints this dictionary. Keys are bitstrings. Values are tallies.",
    misconception: "The biggest count is the statevector. It is the most frequent sample.",
  },
  {
    term: "Histogram",
    plain: "A histogram is a bar chart of counts or probabilities for each measured bitstring.",
    technical: "Composer and Qiskit plot the empirical distribution over computational-basis outcomes.",
    analogyDomain: "Sports",
    analogy: "A bar for each possible scoreline after many plays.",
    why: "The Bell lab’s ideal histogram is mostly two bars, 00 and 11.",
    misconception: "Every bar you see on hardware is a mistake. Small unexpected bars can be noise. On an ideal simulator they should be absent or negligible.",
  },
  {
    term: "Simulator",
    plain: "A simulator is an ordinary computer calculating what an ideal, or sometimes a noisy, quantum circuit would do.",
    technical: "A statevector simulator stores the 2ⁿ amplitudes and samples them. It is not a quantum processing unit.",
    analogyDomain: "Cooking",
    analogy: "A practice kitchen that follows the recipe with perfect measurements and no burnt pans. Useful for learning. It is not dinner service on a busy Saturday.",
    why: "We run the ideal simulation first so you know what the circuit is prepared to do.",
    misconception: "A simulator result is a quantum-advantage result. It is a classical calculation of the model.",
  },
  {
    term: "Quantum processing unit or QPU",
    pronunciation: "Q-P-U",
    plain: "A QPU is the quantum hardware that runs circuits on real qubits.",
    technical: "IBM Quantum QPUs execute transpiled circuits on superconducting qubits. Results include noise from the device and the environment.",
    analogyDomain: "Home Depot",
    analogy: "The real job site, not the drawing on the counter. Weather, tools, and materials affect the outcome. The drawing is still the plan.",
    why: "If you later run the same circuit on hardware, you compare the ideal histogram with the QPU histogram. That job uses Open Plan time.",
    misconception: "A QPU replaces the need for classical computers. Real projects use both. The Hetionet example is hybrid on purpose.",
  },
  {
    term: "Noise",
    plain: "Noise is unwanted disturbance that makes hardware results differ from the ideal state.",
    technical: "Decoherence, gate errors, readout errors, and crosstalk change probabilities so unexpected bitstrings appear.",
    analogyDomain: "Music",
    analogy: "Hum in a recording. The song is still there. Extra sound shows up in the quiet parts.",
    why: "A few 01 or 10 counts on hardware, in this Bell lab, are a teaching example of noise, not a new entangled state.",
    misconception: "Noise means the device is not quantum. It means the device is a physical system.",
  },
  {
    term: "Error",
    plain: "An error is a specific failure: a gate that did not do exactly what the circuit asked, or a measurement that was read wrong.",
    technical: "Gate error and readout assignment error are quantified in device calibration data. Error mitigation and correction are later topics.",
    analogyDomain: "Sports",
    analogy: "A dropped pass on a play that was called correctly. The playbook was right. The execution slipped.",
    why: "It helps to tell a Python bug, a circuit that does not match the plan, and a hardware error apart from each other.",
    misconception: "Any result that is not exactly 512 and 512 is an error. Finite shots fluctuate even in an ideal simulation.",
  },
  {
    term: "Transpilation",
    pronunciation: "trans-pih-LAY-shun",
    plain: "Transpilation rewrites your circuit so a particular backend can run it, using the gates and connections that machine actually has.",
    technical: "The transpiler maps abstract gates onto a backend’s basis gates and coupling map, and may optimize that mapping.",
    analogyDomain: "Home Depot",
    analogy: "Turning a design sketch into a cut list for the tools in this store. A different store may need a different cut list for the same design.",
    why: "You can ignore it for the ideal two-qubit simulation. It matters as soon as you choose a real backend.",
    misconception: "Transpilation changes the problem you meant to solve. It changes the implementation so the hardware can express that circuit.",
  },
  {
    term: "Backend",
    plain: "A backend is the simulator or QPU you ask to run a circuit.",
    technical: "In IBM Quantum and Qiskit Runtime, a backend is a named execution target with its own configuration and, for hardware, calibration.",
    analogyDomain: "Cooking",
    analogy: "Which kitchen you send the ticket to: the practice kitchen or a particular restaurant line.",
    why: "Composer asks you to choose where to run. The lab starts with an ideal simulation option when it is available.",
    misconception: "The backend is your IBM Cloud region. Region and account matter for access. The backend is the compute target.",
  },
  {
    term: "Qiskit",
    pronunciation: "KIZ-kit",
    plain: "Qiskit is IBM’s open-source toolkit for writing and running quantum circuits in Python.",
    technical: "This workshop pins the Qiskit 2.3 line and uses QuantumCircuit, Statevector, and StatevectorSampler.",
    analogyDomain: "Home Depot",
    analogy: "The tool brand you use to build the same project you just laid out on the Composer workbench.",
    why: "Composer is the visual tool. Qiskit is the code tool. They describe the same circuit.",
    misconception: "Qiskit is the quantum computer. It is software.",
  },
  {
    term: "IBM Quantum Composer",
    plain: "Composer is the visual circuit editor in the IBM Quantum Platform. You drag gates onto qubit wires.",
    technical: "Composer builds OpenQASM-level circuits, shows state information, and can submit jobs to simulators or accessible QPUs.",
    analogyDomain: "Music",
    analogy: "A piano roll. Time moves left to right. Each row is a qubit. Blocks are gates.",
    why: "The first lab is visual so Python does not get in the way of the idea.",
    misconception: "Composer is a different kind of quantum computer from Qiskit. It is a different way to write the program.",
  },
  {
    term: "Quantum kernel",
    plain: "A quantum kernel is a way of comparing two data points by using a quantum circuit, often so a classical classifier can use that comparison.",
    technical: "A fidelity quantum kernel estimates overlaps of quantum states prepared by a feature map. QSVC uses such a kernel.",
    analogyDomain: "Music",
    analogy: "Judging how close two songs are by how they sound after the same arrangement, rather than by comparing the raw lyric sheets alone.",
    why: "The Hetionet example uses quantum kernels inside QSVC. You will not retrain that model in this workshop.",
    misconception: "A quantum kernel replaces the dataset. It is a comparison method inside a larger classical workflow.",
  },
  {
    term: "Feature map",
    plain: "A feature map is the circuit pattern that loads classical numbers into a quantum state.",
    technical: "The Hetionet repository’s best reported quantum path uses a Pauli feature map with two repetitions on 16 features.",
    analogyDomain: "Cooking",
    analogy: "The way you translate a written grocery order into ingredients actually in the pan. Different translations (ZZ versus Pauli) are different maps.",
    why: "Changing the feature map changed the Hetionet scores. The map is a design choice, not a guarantee.",
    misconception: "There is one correct feature map for all data. The repository compares maps and reports the result.",
  },
  {
    term: "Benchmark",
    plain: "A benchmark is a fair test you can repeat, used to compare methods.",
    technical: "In the Hetionet project, models are compared on the same prediction task with PR-AUC on held-out or cross-validated splits, as documented in that repository.",
    analogyDomain: "Sports",
    analogy: "Everyone runs the same course. You do not compare a sprint to a marathon and declare a winner.",
    why: "Without a benchmark, a quantum experiment is a demo, not evidence.",
    misconception: "A benchmark is a leaderboard you must top to justify learning. It is a measurement habit.",
  },
  {
    term: "Baseline",
    plain: "A baseline is a strong, simpler method you compare against before claiming a new method helped.",
    technical: "The Hetionet README reports optimized RandomForest and ExtraTrees classical baselines beside QSVC and stacking ensembles.",
    analogyDomain: "Sports",
    analogy: "The current team record. A new play is interesting if you know what the old play already achieved.",
    why: "The best published number in that README is a hybrid stack, and a classical forest is close behind. That is the honest story.",
    misconception: "If a quantum model beats a weak baseline, the problem needs a quantum computer. Beat a serious baseline, and still ask whether the gain is worth the cost.",
  },
  {
    term: "Hybrid quantum-classical workflow",
    plain: "A hybrid workflow uses ordinary computers and quantum circuits in one project, each where it fits.",
    technical: "Hetionet’s documented pipeline embeds a knowledge graph classically, engineers features, trains classical models, evaluates quantum kernels and QSVC, and combines them in a stacking ensemble.",
    analogyDomain: "Home Depot",
    analogy: "A renovation that uses both hand tools and one specialized cutter. The specialized cutter does not frame the house.",
    why: "This is the shape of realistic near-term projects, including Fall Fest projects.",
    misconception: "Hybrid means the quantum part is decorative. In the documented run, the quantum model is a real component that is measured against baselines.",
  },
  {
    term: "Quantum advantage",
    plain: "Quantum advantage would mean a quantum method beats the best practical classical method on a useful task by a margin that matters.",
    technical: "It is an empirical and problem-specific claim. This workshop does not attempt it, and the Hetionet results are not presented as advantage.",
    analogyDomain: "Sports",
    analogy: "Winning a championship, not winning a scrimmage against a partial roster.",
    why: "Participants should be able to hear the phrase and not treat this Bell lab as an example of it.",
    misconception: "Any circuit that runs on a QPU is quantum advantage. Running is access. Advantage is a comparative claim.",
  },
  {
    term: "Quantum readiness",
    plain: "Quantum readiness is knowing why you are exploring quantum computing, who must be involved, what you will learn, and how you will judge progress.",
    technical: "In this workshop the discussion covers strategy, technology, talent, risk, ecosystems, use-case selection, and workforce pathways, attributed to the leadership themes in Robert Loredo’s Quantum Readiness for Leaders and interpreted for Fall Fest by Quantum Global Group.",
    analogyDomain: "Home Depot",
    analogy: "Readiness is having the plan, the permits, the crew, and a way to inspect the work. It is not already owning every tool in the aisle.",
    why: "It is the point of the Florida Quantum Readiness Challenge onboarding, not a side topic.",
    misconception: "Readiness means waiting until you understand all of the physics. It means starting with a clear question and an honest evaluation plan.",
  },
];

export const REQUIRED_TERMS = [
  "Classical bit",
  "Qubit",
  "State",
  "Statevector",
  "Basis state",
  "Amplitude",
  "Probability",
  "Phase",
  "Superposition",
  "Entanglement",
  "Quantum gate",
  "Hadamard gate",
  "X gate",
  "CNOT or CX gate",
  "Control qubit",
  "Target qubit",
  "Quantum circuit",
  "Quantum register",
  "Classical register",
  "Measurement",
  "Shot",
  "Counts",
  "Histogram",
  "Simulator",
  "Quantum processing unit or QPU",
  "Noise",
  "Error",
  "Transpilation",
  "Backend",
  "Qiskit",
  "IBM Quantum Composer",
  "Quantum kernel",
  "Feature map",
  "Benchmark",
  "Baseline",
  "Hybrid quantum-classical workflow",
  "Quantum advantage",
  "Quantum readiness",
] as const;
